SCR_MissionHeader {
 World "{4B6A98B587987C23}Worlds/COALobby/novka/unnamed.ent"
 m_sName "Landing At Point Rain - LNRF"
 m_sAuthor "fluff_"
 m_sDescription "Good thing those bugs can't aim..."
 m_sDetails "Good thing those bugs can't aim..."
 m_sIcon "{C12646EF43AFA171}Images/Screenshot (219).edds"
 m_sLoadingScreen "{C12646EF43AFA171}Images/Screenshot (219).edds"
 m_sPreviewImage "{C12646EF43AFA171}Images/Screenshot (219).edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_fWeaponFiredReactionDistance 505
 m_eCombatMode GREEN
 m_fPerceptionSafe 1.5
 m_fPerceptionVigilant 3.5
 m_fAimAccuracyErrorModifier 1
 m_sTerrainName "Novka"
}